import { db } from "./db";
import { tutorials, kits, creators } from "@shared/schema";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Seeding database...");

  const existingTutorials = await db.select().from(tutorials);
  if (existingTutorials.length > 0) {
    console.log("Database already seeded. Skipping.");
    process.exit(0);
  }

  await db.insert(tutorials).values([
    {
      id: "t1",
      title: "Mastering Urban Composting: Small Space Solutions",
      thumbnail: "/images/tutorial-garden.png",
      videoUrl: "https://www.youtube.com/watch?v=LKAUY31_q_s",
      category: "Compost",
      duration: "12:45",
      difficulty: "Beginner",
      views: 1250,
      creator: "EcoGardener Jane",
      tags: ["compost", "urban", "sustainable", "apartment"],
      description: "Learn how to create rich compost even in a small apartment using bokashi and vermiculture techniques.",
      language: "English",
    },
    {
      id: "t2",
      title: "Natural Pest Control: Neem Oil & Garlic Spray",
      thumbnail: "/images/tutorial-pest.png",
      videoUrl: "https://youtu.be/VjxKkm9khJk",
      category: "Bio-pesticide",
      duration: "08:20",
      difficulty: "Beginner",
      views: 890,
      creator: "Organic Mike",
      tags: ["pest control", "neem", "garlic", "organic"],
      description: "Stop aphids and mites naturally without harming beneficial insects. A simple recipe using kitchen ingredients.",
      language: "English",
    },
    {
      id: "t3",
      title: "Soil Health 101: The Soil Food Web",
      thumbnail: "/images/tutorial-soil.png",
      videoUrl: "https://www.youtube.com/embed/uAMniWJm2vo",
      category: "Soil Health",
      duration: "25:00",
      difficulty: "Intermediate",
      views: 3400,
      creator: "Dr. Green",
      tags: ["soil", "organic", "biology", "microbes"],
      description: "Understand the microscopic life in your soil and how to nurture it for explosive plant growth.",
      language: "English",
    },
    {
      id: "t4",
      title: "Liquid Gold: Making Compost Tea",
      thumbnail: "/images/tutorial-compost-tea.png",
      videoUrl: "https://www.youtube.com/watch?v=EH6IBAsNZPE",
      category: "Fertilizer",
      duration: "10:30",
      difficulty: "Beginner",
      views: 1560,
      creator: "Compost King",
      tags: ["fertilizer", "compost", "organic", "tea"],
      description: "Brew the perfect compost tea to supercharge your garden's microbial life.",
      language: "English",
    },
    {
      id: "t5",
      title: "Winter Gardening: Growing in the Cold",
      thumbnail: "/images/tutorial-winter.png",
      videoUrl: "https://youtu.be/Jtw7pnqFeS4",
      category: "Planting",
      duration: "14:10",
      difficulty: "Intermediate",
      views: 2890,
      creator: "ColdFrame Clara",
      tags: ["winter", "greenhouse", "seeds", "cold weather"],
      description: "Keep your garden productive year-round with cold frames and frost-resistant varieties.",
      language: "English",
    },
    {
      id: "t6",
      title: "Building Raised Beds for Maximum Yield",
      thumbnail: "/images/tutorial-raised-bed.png",
      videoUrl: "https://www.youtube.com/embed/RY432YI7SoE",
      category: "Planting",
      duration: "18:15",
      difficulty: "Beginner",
      views: 5200,
      creator: "The Bed Builder",
      tags: ["raised beds", "construction", "garden", "diy"],
      description: "Step-by-step guide to building raised beds that maximize yield and minimize back strain.",
      language: "English",
    },
    {
      id: "t7",
      title: "Companion Planting: Nature's Best Partnerships",
      thumbnail: "/images/tutorial-garden.png",
      videoUrl: "https://www.youtube.com/shorts/tZJpo5N28zc",
      category: "Planting",
      duration: "16:40",
      difficulty: "Intermediate",
      views: 4100,
      creator: "Garden Guru",
      tags: ["companion planting", "biodiversity", "organic", "polyculture"],
      description: "Discover which plants grow better together and how to design a thriving polyculture garden.",
      language: "English",
    },
    {
      id: "t8",
      title: "Vermicomposting: Let Worms Do the Work",
      thumbnail: "/images/tutorial-soil.png",
      videoUrl: "https://www.youtube.com/watch?v=Z5ozNM-Hb0w",
      category: "Compost",
      duration: "11:55",
      difficulty: "Beginner",
      views: 2300,
      creator: "Worm Whisperer",
      tags: ["vermicompost", "worms", "organic", "indoor"],
      description: "Set up a worm bin and produce the richest compost possible, even indoors.",
      language: "English",
    },
  ]);

  await db.insert(kits).values([
    {
      id: "k1",
      name: "Urban Composter Starter Kit",
      image: "/images/kit-compost.png",
      price: 3750,
      rating: 4.8,
      reviews: 120,
      description: "Everything you need to start composting in a small apartment using bokashi and vermiculture techniques.",
      isAffiliate: true,
      commission: 10,
      tags: ["compost", "urban", "beginner"],
    },
    {
      id: "k2",
      name: "Organic Heirloom Seed Collection",
      image: "/images/kit-seeds.png",
      price: 2499,
      rating: 4.9,
      reviews: 340,
      description: "20 varieties of non-GMO, heirloom vegetable seeds. Perfect for biodiversity.",
      isAffiliate: true,
      commission: 15,
      tags: ["seeds", "heirloom", "organic", "biodiversity"],
    },
    {
      id: "k3",
      name: "Professional Soil Test Kit",
      image: "/images/kit-soil.png",
      price: 2950,
      rating: 4.6,
      reviews: 85,
      description: "Test your soil pH, N, P, and K levels at home. Essential for precise nutrient management.",
      isAffiliate: true,
      commission: 8,
      tags: ["soil", "testing", "nutrients", "science"],
    },
    {
      id: "k4",
      name: "Automatic Drip Irrigation System",
      image: "/images/kit-irrigation.png",
      price: 7450,
      rating: 4.7,
      reviews: 210,
      description: "Save water and time with this easy-to-install drip system. Adjustable emitters.",
      isAffiliate: true,
      commission: 12,
      tags: ["irrigation", "water", "automation", "garden"],
    },
    {
      id: "k5",
      name: "Neem Oil Cold-Pressed Concentrate",
      image: "/images/kit-compost.png",
      price: 850,
      rating: 4.5,
      reviews: 560,
      description: "Pure cold-pressed neem oil for organic pest control. Makes 50+ liters of spray.",
      isAffiliate: true,
      commission: 20,
      tags: ["neem", "pest control", "organic", "concentrate"],
    },
    {
      id: "k6",
      name: "Raised Bed Garden Kit (Cedar)",
      image: "/images/kit-seeds.png",
      price: 5999,
      rating: 4.8,
      reviews: 175,
      description: "Pre-cut cedar planks, hardware, and liner. Assemble a 4x8 raised bed in 30 minutes.",
      isAffiliate: true,
      commission: 10,
      tags: ["raised bed", "cedar", "diy", "construction"],
    },
  ]);

  await db.insert(creators).values([
    {
      id: "c1",
      name: "EcoGardener Jane",
      avatar: "https://i.pravatar.cc/100?img=11",
      engagementScore: 98,
      totalViews: 45200,
      tutorialCount: 12,
      category: "Compost",
      isNew: false,
    },
    {
      id: "c2",
      name: "Dr. Green",
      avatar: "https://i.pravatar.cc/100?img=12",
      engagementScore: 95,
      totalViews: 38000,
      tutorialCount: 8,
      category: "Soil Health",
      isNew: false,
    },
    {
      id: "c3",
      name: "Organic Mike",
      avatar: "https://i.pravatar.cc/100?img=13",
      engagementScore: 92,
      totalViews: 21500,
      tutorialCount: 5,
      category: "Bio-pesticide",
      isNew: false,
    },
    {
      id: "c4",
      name: "Compost King",
      avatar: "https://i.pravatar.cc/100?img=14",
      engagementScore: 88,
      totalViews: 15600,
      tutorialCount: 4,
      category: "Fertilizer",
      isNew: true,
    },
    {
      id: "c5",
      name: "ColdFrame Clara",
      avatar: "https://i.pravatar.cc/100?img=15",
      engagementScore: 85,
      totalViews: 12800,
      tutorialCount: 3,
      category: "Planting",
      isNew: true,
    },
    {
      id: "c6",
      name: "The Bed Builder",
      avatar: "https://i.pravatar.cc/100?img=16",
      engagementScore: 82,
      totalViews: 9200,
      tutorialCount: 2,
      category: "Planting",
      isNew: true,
    },
    {
      id: "c7",
      name: "Garden Guru",
      avatar: "https://i.pravatar.cc/100?img=17",
      engagementScore: 90,
      totalViews: 28000,
      tutorialCount: 7,
      category: "Planting",
      isNew: false,
    },
    {
      id: "c8",
      name: "Worm Whisperer",
      avatar: "https://i.pravatar.cc/100?img=18",
      engagementScore: 78,
      totalViews: 6400,
      tutorialCount: 2,
      category: "Compost",
      isNew: true,
    },
  ]);

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
